### ISSUE TITLE
How to specify a route for only one language?

### ISSUE THREAD

**Issue by luminarious** [paulgv/nuxt-i18n#2]
Right now the routes are generated per language. How would I specify that I want a route to be available in just one language?

Using _locale as the first param caused some issues before, but at least we could easily separate pages that are localized and pages that should be used as-is.

```
/pages/_locale/index.vue
/pages/en/styleguide.vue
```

**Comment by paulgv** [comment]
Hi @luminarious 
That's an interesting point. I just opened a PR with a possible solution, I'd be curious to have to opinion on this. I added a new option `ignoreRoutes` which you can use to list routes that should be skipped when generating localized routes: https://github.com/paulgv/nuxt-i18n/pull/3

In your specific case, `ignoreRoutes` would look like this:
```js
ignoreRoutes: [
  'en-styleguide'
]
```

You can give this specific branch a try in your project:

```sh
yarn add https://github.com/paulgv/nuxt-i18n.git#feature/ignore-routes-localization
```

**Comment by paulgv** [comment]
https://github.com/paulgv/nuxt-i18n/pull/3
